### ISSUE TITLE
Descriptions contain closing </info> tags while opening tags are missing

### ISSUE THREAD

**Issue by linawolf** [garvinhicking/clinspector_gadget#2]
See for example when your run it in core api in TYPO3 v12

**Comment by linawolf** [comment]
See for example here: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4772/files#diff-228e5a66d69ce8eaee0405b33585900e0c08cb8ac590e1ae42c92658245fd96bR1535

**Comment by linawolf** [comment]
Same happens in main: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4786/files#diff-228e5a66d69ce8eaee0405b33585900e0c08cb8ac590e1ae42c92658245fd96bR1241

**Comment by linawolf** [comment]
Strange enough before applying JSON pretty-print the starting tags where not missing...

**Comment by garvinhicking** [comment]
Closed via 64ce8e0fcb91ab1f8ba1d70857790340b5652fc1
